.decl base(x:number, y:number)
.input base
.decl e(x:number, y:number)
.input e
.decl blocked(x:number)
.input blocked
.decl r1(x:number, y:number)
.decl r2(x:number, y:number)
.decl s(x:number)
.decl p(x:number, y:number)
.decl out(y:number)
.output out
.decl sup_p_bf_r0_0(c0:number)
.decl sup_p_bf_r0_1(c0:number, c1:number)
.decl p_bf(c0:number, c1:number)
.decl sup_p_bf_r1_0(c0:number)
.decl sup_p_bf_r1_1(c0:number, c1:number)
.decl sup_p_bf_r1_2(c0:number, c1:number)
.decl sup_p_bf_r1_3(c0:number, c1:number)
.decl magic_p_bf(c0:number)
.decl magic_s_b(c0:number)
.decl magic_r1_bf(c0:number)
.decl sup_s_b_r0_0(c0:number)
.decl sup_s_b_r0_1(c0:number, c1:number)
.decl sup_s_b_r0_2(c0:number)
.decl s_b(c0:number)
.decl sup_r1_bf_r0_0(c0:number)
.decl sup_r1_bf_r0_1(c0:number, c1:number)
.decl r1_bf(c0:number, c1:number)
.decl sup_r1_bf_r1_0(c0:number)
.decl sup_r1_bf_r1_1(c0:number, c1:number)
.decl sup_r1_bf_r1_2(c0:number, c1:number)
.decl magic_r2_bf(c0:number)
.decl sup_r2_bf_r0_0(c0:number)
.decl sup_r2_bf_r0_1(c0:number, c1:number)
.decl r2_bf(c0:number, c1:number)
sup_p_bf_r0_0(x) :- magic_p_bf(x).
sup_p_bf_r0_1(x, y) :- sup_p_bf_r0_0(x), e(x, y).
p_bf(x, y) :- sup_p_bf_r0_1(x, y).
sup_p_bf_r1_0(x) :- magic_p_bf(x).
sup_p_bf_r1_1(x, z) :- sup_p_bf_r1_0(x), p_bf(x, z).
sup_p_bf_r1_2(x, z) :- sup_p_bf_r1_1(x, z), !s_b(z).
sup_p_bf_r1_3(x, y) :- sup_p_bf_r1_2(x, z), r1_bf(z, y).
magic_p_bf(x) :- sup_p_bf_r1_0(x).
magic_s_b(z) :- sup_p_bf_r1_1(x, z).
magic_r1_bf(z) :- sup_p_bf_r1_2(x, z).
p_bf(x, y) :- sup_p_bf_r1_3(x, y).
sup_s_b_r0_0(x) :- magic_s_b(x).
sup_s_b_r0_1(x, y) :- sup_s_b_r0_0(x), r1_bf(x, y).
sup_s_b_r0_2(x) :- sup_s_b_r0_1(x, y), blocked(y).
magic_r1_bf(x) :- sup_s_b_r0_0(x).
s_b(x) :- sup_s_b_r0_2(x).
sup_r1_bf_r0_0(x) :- magic_r1_bf(x).
sup_r1_bf_r0_1(x, y) :- sup_r1_bf_r0_0(x), base(x, y).
r1_bf(x, y) :- sup_r1_bf_r0_1(x, y).
sup_r1_bf_r1_0(x) :- magic_r1_bf(x).
sup_r1_bf_r1_1(x, z) :- sup_r1_bf_r1_0(x), r2_bf(x, z).
sup_r1_bf_r1_2(x, y) :- sup_r1_bf_r1_1(x, z), base(z, y).
magic_r2_bf(x) :- sup_r1_bf_r1_0(x).
r1_bf(x, y) :- sup_r1_bf_r1_2(x, y).
sup_r2_bf_r0_0(x) :- magic_r2_bf(x).
sup_r2_bf_r0_1(x, y) :- sup_r2_bf_r0_0(x), r1_bf(x, y).
magic_r1_bf(x) :- sup_r2_bf_r0_0(x).
r2_bf(x, y) :- sup_r2_bf_r0_1(x, y).
magic_p_bf(1).
out(y) :- p_bf(1, y).
