.decl ancestor(x:number, y:number) 
.decl nonancestor(x:number, y:number) 
.decl parent(child:number, par:number) 
.decl person(x:number) 
.decl q_nonancestor(y:number) 
ancestor(x,y) :- 
   parent(x,y).

ancestor(x,y) :- 
   parent(x,z),
   ancestor(z,y).

nonancestor(x,y) :- 
   person(x),
   person(y),
   !ancestor(x,y).

q_nonancestor(y) :- 
   nonancestor(1,y).
.input parent(IO="file",attributeNames="child	par",fact-dir=".",name="parent",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["child", "par"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["i:number", "i:number"]}}")

.input person(IO="file",attributeNames="x",fact-dir=".",name="person",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["i:number"]}}")

.output q_nonancestor(IO="file",attributeNames="y",name="q_nonancestor",operation="output",output-dir=".",params="{"records": {}, "relation": {"arity": 1, "params": ["y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["i:number"]}}")

