.decl edge(a:number, b:number) 
.decl q_tc(y:number) 
.decl tc(a:number, b:number) 
q_tc(y) :- 
   tc(1,y).

tc(x,y) :- 
   edge(x,y).

tc(x,y) :- 
   tc(x,z),
   edge(z,y).
.input edge(IO="file",attributeNames="a	b",fact-dir=".",name="edge",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["a", "b"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["i:number", "i:number"]}}")

.output q_tc(IO="file",attributeNames="y",name="q_tc",operation="output",output-dir=".",params="{"records": {}, "relation": {"arity": 1, "params": ["y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["i:number"]}}")

