.decl @magic.tc.{bf}(a:number) 
.decl edge(a:number, b:number) 
.decl q_tc(y:number) 
.decl tc.{bf}(a:number, b:number) 
@magic.tc.{bf}(1).

q_tc(y) :- 
   tc.{bf}(@abdul0,y),
   @abdul0 = 1.

tc.{bf}(x,y) :- 
   @magic.tc.{bf}(x),
   edge(x,y).

tc.{bf}(x,y) :- 
   @magic.tc.{bf}(x),
   tc.{bf}(x,z),
   edge(z,y).
.input edge(IO="file",attributeNames="a	b",fact-dir=".",name="edge",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["a", "b"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["i:number", "i:number"]}}")

.output q_tc(IO="file",attributeNames="y",name="q_tc",operation="output",output-dir=".",params="{"records": {}, "relation": {"arity": 1, "params": ["y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["i:number"]}}")

