.decl base(x:number, y:number)
.input base
.decl e(x:number, y:number)
.input e
.decl blocked(x:number)
.input blocked
.decl sibling_edge(x:number, y:number)
.input sibling_edge
.decl q(x:number, y:number)
.decl s(x:number)
.decl p(x:number, y:number)
.decl out(y:number)
.output out
.decl tc(x:number, y:number)
.decl out2(y:number)
.output out2
out2(y) :- tc(1, y).
p(x, y) :- e(x, y).
p(x, y) :- p(x, z), !s(z), q(z, y).
q(x, y) :- base(x, y).
q(x, y) :- q(x, z), base(z, y).
s(x) :- q(x, y), blocked(y).
tc(x, y) :- sibling_edge(x, y).
tc(x, y) :- tc(x, z), sibling_edge(z, y).
out(y) :- p(1, y).
