#!/usr/bin/env python3
"""
NIGHT-BATCH-01 T7 item 2: golden-file generation. CLAUDE.md section 6:
"Golden files in tests/golden/ are generated by Soufflé and never by
dlc. If you ever regenerate a golden file from our own output, you have
destroyed the oracle and must say so loudly." This module is the one
place golden files get written, specifically so that rule has exactly
one enforcement point.

generate_golden() refuses (raises GoldenGuardError) unless the
generating command's argv[0] is literally "souffle". There is no bypass
flag. If dlc ever needs to write something that looks like a golden
file, it must not go through this function.
"""
import json
import subprocess
from pathlib import Path

GOLDEN_ROOT = Path(__file__).resolve().parents[1] / "tests" / "golden"


class GoldenGuardError(Exception):
    pass


def generate_golden(name: str, dl_path: Path, facts_dir: Path, generating_cmd: list):
    """Run `generating_cmd` (must be a souffle invocation) and copy its
    output relations into tests/golden/<name>/. Raises GoldenGuardError
    without running anything if generating_cmd doesn't start with
    "souffle" (accepting a bare name or a path ending in "souffle", to
    allow absolute-path invocations)."""
    prog = Path(generating_cmd[0]).name
    if prog != "souffle":
        raise GoldenGuardError(
            f"refusing to generate golden file '{name}': generating command "
            f"is {generating_cmd[0]!r}, not souffle. Golden files must come "
            f"from the oracle only (CLAUDE.md section 6)."
        )

    dl_path = Path(dl_path).resolve()
    facts_dir = Path(facts_dir).resolve()
    out_dir = GOLDEN_ROOT / name
    out_dir.mkdir(parents=True, exist_ok=True)

    import re
    output_names = sorted(set(re.findall(r"^\s*\.output\s+(\w+)", dl_path.read_text(), re.MULTILINE)))

    cmd = list(generating_cmd) + ["-F", str(facts_dir), "-D", str(out_dir), str(dl_path)]
    proc = subprocess.run(cmd, cwd=str(out_dir), capture_output=True, text=True, timeout=300)
    if proc.returncode != 0:
        raise RuntimeError(f"souffle failed generating golden '{name}': {proc.stderr}")

    manifest = {
        "name": name,
        "source_dl": str(dl_path),
        "facts_dir": str(facts_dir),
        "generating_cmd": cmd,
        "output_relations": output_names,
    }
    (out_dir / "GOLDEN_MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return out_dir
