.decl base(x:number, y:number)
.input base
.decl e(x:number, y:number)
.input e
.decl blocked(x:number)
.input blocked
.decl q(x:number, y:number)
.decl s(x:number)
.decl p(x:number, y:number)
.decl parent(child:number, par:number)
.input parent
.decl person(x:number)
.input person
.decl ancestor(x:number, y:number)
.decl nonancestor(x:number, y:number)
.decl combo(x:number, y:number)
.decl ans(y:number)
.output ans
.decl sup_combo_bf_r0_0(c0:number)
.decl sup_combo_bf_r0_1(c0:number, c1:number)
.decl sup_combo_bf_r0_2(c0:number, c1:number)
.decl magic_nonancestor_bb(c0:number, c1:number)
.decl combo_bf(c0:number, c1:number)
.decl sup_nonancestor_bb_r0_0(c0:number, c1:number)
.decl sup_nonancestor_bb_r0_1(c0:number, c1:number)
.decl sup_nonancestor_bb_r0_2(c0:number, c1:number)
.decl sup_nonancestor_bb_r0_3(c0:number, c1:number)
.decl magic_ancestor_bb(c0:number, c1:number)
.decl nonancestor_bb(c0:number, c1:number)
.decl sup_ancestor_bb_r0_0(c0:number, c1:number)
.decl sup_ancestor_bb_r0_1(c0:number, c1:number)
.decl ancestor_bb(c0:number, c1:number)
.decl sup_ancestor_bb_r1_0(c0:number, c1:number)
.decl sup_ancestor_bb_r1_1(c0:number, c1:number, c2:number)
.decl sup_ancestor_bb_r1_2(c0:number, c1:number)
.decl magic_combo_bf(c0:number)
p(x, y) :- e(x, y).
p(x, y) :- p(x, z), !s(z), q(z, y).
q(x, y) :- base(x, y).
q(x, y) :- q(x, z), base(z, y).
s(x) :- q(x, y), blocked(y).
sup_combo_bf_r0_0(x) :- magic_combo_bf(x).
sup_combo_bf_r0_1(x, y) :- sup_combo_bf_r0_0(x), p(x, y).
sup_combo_bf_r0_2(x, y) :- sup_combo_bf_r0_1(x, y), nonancestor_bb(x, y).
magic_nonancestor_bb(x, y) :- sup_combo_bf_r0_1(x, y).
combo_bf(x, y) :- sup_combo_bf_r0_2(x, y).
sup_nonancestor_bb_r0_0(x, y) :- magic_nonancestor_bb(x, y).
sup_nonancestor_bb_r0_1(x, y) :- sup_nonancestor_bb_r0_0(x, y), person(x).
sup_nonancestor_bb_r0_2(x, y) :- sup_nonancestor_bb_r0_1(x, y), person(y).
sup_nonancestor_bb_r0_3(x, y) :- sup_nonancestor_bb_r0_2(x, y), !ancestor_bb(x, y).
magic_ancestor_bb(x, y) :- sup_nonancestor_bb_r0_2(x, y).
nonancestor_bb(x, y) :- sup_nonancestor_bb_r0_3(x, y).
sup_ancestor_bb_r0_0(x, y) :- magic_ancestor_bb(x, y).
sup_ancestor_bb_r0_1(x, y) :- sup_ancestor_bb_r0_0(x, y), parent(x, y).
ancestor_bb(x, y) :- sup_ancestor_bb_r0_1(x, y).
sup_ancestor_bb_r1_0(x, y) :- magic_ancestor_bb(x, y).
sup_ancestor_bb_r1_1(x, y, z) :- sup_ancestor_bb_r1_0(x, y), parent(x, z).
sup_ancestor_bb_r1_2(x, y) :- sup_ancestor_bb_r1_1(x, y, z), ancestor_bb(z, y).
magic_ancestor_bb(z, y) :- sup_ancestor_bb_r1_1(x, y, z).
ancestor_bb(x, y) :- sup_ancestor_bb_r1_2(x, y).
magic_combo_bf(1).
ans(y) :- combo_bf(1, y).
