.decl edge(a:number, b:number)
.input edge
.decl tc(a:number, b:number)
.decl q_tc(y:number)
.output q_tc
.decl sup_tc_bf_r0_0(c0:number)
.decl sup_tc_bf_r0_1(c0:number, c1:number)
.decl tc_bf(c0:number, c1:number)
.decl sup_tc_bf_r1_0(c0:number)
.decl sup_tc_bf_r1_1(c0:number, c1:number)
.decl sup_tc_bf_r1_2(c0:number, c1:number)
.decl magic_tc_bf(c0:number)
sup_tc_bf_r0_0(x) :- magic_tc_bf(x).
sup_tc_bf_r0_1(x, y) :- sup_tc_bf_r0_0(x), edge(x, y).
tc_bf(x, y) :- sup_tc_bf_r0_1(x, y).
sup_tc_bf_r1_0(x) :- magic_tc_bf(x).
sup_tc_bf_r1_1(x, z) :- sup_tc_bf_r1_0(x), tc_bf(x, z).
sup_tc_bf_r1_2(x, y) :- sup_tc_bf_r1_1(x, z), edge(z, y).
magic_tc_bf(x) :- sup_tc_bf_r1_0(x).
tc_bf(x, y) :- sup_tc_bf_r1_2(x, y).
magic_tc_bf(1).
q_tc(y) :- tc_bf(1, y).
