.decl base(x:number, y:number)
.input base
.decl e(x:number, y:number)
.input e
.decl blocked(x:number)
.input blocked
.decl r1(x:number, y:number)
.decl r2(x:number, y:number)
.decl s(x:number)
.decl p(x:number, y:number)
.decl out(y:number)
.output out
p(x, y) :- e(x, y).
p(x, y) :- p(x, z), !s(z), r1(z, y).
r1(x, y) :- base(x, y).
r1(x, y) :- r2(x, z), base(z, y).
r2(x, y) :- r1(x, y).
s(x) :- r1(x, y), blocked(y).
out(y) :- p(1, y).
