.decl edge(a:number, b:number)
.input edge
.decl node(a:number)
.input node
.decl reach(a:number, b:number)
.decl unreach(a:number, b:number)
.decl q2(b:number)
.output q2
.decl sup_unreach_bf_r0_0(c0:number)
.decl sup_unreach_bf_r0_1(c0:number)
.decl sup_unreach_bf_r0_2(c0:number, c1:number)
.decl sup_unreach_bf_r0_3(c0:number, c1:number)
.decl magic_reach_bb(c0:number, c1:number)
.decl unreach_bf(c0:number, c1:number)
.decl sup_reach_bb_r0_0(c0:number, c1:number)
.decl sup_reach_bb_r0_1(c0:number, c1:number)
.decl reach_bb(c0:number, c1:number)
.decl sup_reach_bb_r1_0(c0:number, c1:number)
.decl sup_reach_bb_r1_1(c0:number, c1:number, c2:number)
.decl sup_reach_bb_r1_2(c0:number, c1:number)
.decl magic_reach_bf(c0:number)
.decl sup_reach_bf_r0_0(c0:number)
.decl sup_reach_bf_r0_1(c0:number, c1:number)
.decl reach_bf(c0:number, c1:number)
.decl sup_reach_bf_r1_0(c0:number)
.decl sup_reach_bf_r1_1(c0:number, c1:number)
.decl sup_reach_bf_r1_2(c0:number, c1:number)
.decl magic_unreach_bf(c0:number)
sup_unreach_bf_r0_0(x) :- magic_unreach_bf(x).
sup_unreach_bf_r0_1(x) :- sup_unreach_bf_r0_0(x), node(x).
sup_unreach_bf_r0_2(x, y) :- sup_unreach_bf_r0_1(x), node(y).
sup_unreach_bf_r0_3(x, y) :- sup_unreach_bf_r0_2(x, y), !reach_bb(x, y).
magic_reach_bb(x, y) :- sup_unreach_bf_r0_2(x, y).
unreach_bf(x, y) :- sup_unreach_bf_r0_3(x, y).
sup_reach_bb_r0_0(x, y) :- magic_reach_bb(x, y).
sup_reach_bb_r0_1(x, y) :- sup_reach_bb_r0_0(x, y), edge(x, y).
reach_bb(x, y) :- sup_reach_bb_r0_1(x, y).
sup_reach_bb_r1_0(x, y) :- magic_reach_bb(x, y).
sup_reach_bb_r1_1(x, y, z) :- sup_reach_bb_r1_0(x, y), reach_bf(x, z).
sup_reach_bb_r1_2(x, y) :- sup_reach_bb_r1_1(x, y, z), edge(z, y).
magic_reach_bf(x) :- sup_reach_bb_r1_0(x, y).
reach_bb(x, y) :- sup_reach_bb_r1_2(x, y).
sup_reach_bf_r0_0(x) :- magic_reach_bf(x).
sup_reach_bf_r0_1(x, y) :- sup_reach_bf_r0_0(x), edge(x, y).
reach_bf(x, y) :- sup_reach_bf_r0_1(x, y).
sup_reach_bf_r1_0(x) :- magic_reach_bf(x).
sup_reach_bf_r1_1(x, z) :- sup_reach_bf_r1_0(x), reach_bf(x, z).
sup_reach_bf_r1_2(x, y) :- sup_reach_bf_r1_1(x, z), edge(z, y).
magic_reach_bf(x) :- sup_reach_bf_r1_0(x).
reach_bf(x, y) :- sup_reach_bf_r1_2(x, y).
magic_unreach_bf(1).
q2(y) :- unreach_bf(1, y).
