.decl base(x:number, y:number)
.input base
.decl e(x:number, y:number)
.input e
.decl blocked(x:number)
.input blocked
.decl gate_seed(x:number)
.input gate_seed
.decl gate_edge(x:number, y:number)
.input gate_edge
.decl q(x:number, y:number)
.decl gate(x:number)
.decl s(x:number)
.decl p(x:number, y:number)
.decl out(y:number)
.output out
gate(x) :- gate_seed(x).
gate(x) :- gate(y), gate_edge(y, x).
p(x, y) :- e(x, y), gate(x).
p(x, y) :- p(x, z), !s(z), q(z, y).
q(x, y) :- base(x, y).
q(x, y) :- q(x, z), base(z, y).
s(x) :- q(x, y), blocked(y).
out(y) :- p(1, y).
