package codegen

const preludeTemplate = `// Generated by dlc codegen (src/codegen). Do not edit by hand.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

// --- string interning: a naive growable array + linear scan, matching
// ir.StringTable's own naive-by-design choice (ir/DESIGN.md) --
// correctness first, nothing here needs to be fast for M1's scope. ---
static char **str_table = NULL;
static size_t str_len = 0, str_cap = 0;

static int64_t intern(const char *s) {
	for (size_t i = 0; i < str_len; i++) {
		if (strcmp(str_table[i], s) == 0) return (int64_t)i;
	}
	if (str_len == str_cap) {
		str_cap = str_cap ? str_cap * 2 : 16;
		str_table = realloc(str_table, str_cap * sizeof(char *));
	}
	str_table[str_len] = strdup(s);
	return (int64_t)(str_len++);
}

static const char *str_lookup(int64_t id) {
	return str_table[id];
}

// A generic-enough line reader for .facts files: splits on '\t', at most
// MAX_COLS columns. Returns the number of columns found, or -1 on EOF.
#define MAX_COLS 32
static int read_facts_line(FILE *f, char cols[MAX_COLS][256]) {
	char line[8192];
	if (!fgets(line, sizeof(line), f)) return -1;
	size_t len = strlen(line);
	while (len > 0 && (line[len-1] == '\n' || line[len-1] == '\r')) line[--len] = 0;
	if (len == 0) return 0; // blank line, caller skips
	int n = 0;
	char *p = line;
	while (n < MAX_COLS) {
		char *tab = strchr(p, '\t');
		size_t clen = tab ? (size_t)(tab - p) : strlen(p);
		if (clen >= 256) clen = 255;
		memcpy(cols[n], p, clen);
		cols[n][clen] = 0;
		n++;
		if (!tab) break;
		p = tab + 1;
	}
	return n;
}
`
