.decl base(x:number, y:number)
.input base
.decl e(x:number, y:number)
.input e
.decl blocked(x:number)
.input blocked
.decl gate_seed(x:number)
.input gate_seed
.decl gate_edge(x:number, y:number)
.input gate_edge
.decl sibling_edge(x:number, y:number)
.input sibling_edge
.decl q(x:number, y:number)
.decl gate(x:number)
.decl s(x:number)
.decl p(x:number, y:number)
.decl out(y:number)
.output out
.decl tc(x:number, y:number)
.decl out2(y:number)
.output out2
.decl sup_tc_bf_r0_0(c0:number)
.decl sup_tc_bf_r0_1(c0:number, c1:number)
.decl tc_bf(c0:number, c1:number)
.decl sup_tc_bf_r1_0(c0:number)
.decl sup_tc_bf_r1_1(c0:number, c1:number)
.decl sup_tc_bf_r1_2(c0:number, c1:number)
.decl magic_tc_bf(c0:number)
gate(x) :- gate_seed(x).
gate(x) :- gate(y), gate_edge(y, x).
p(x, y) :- e(x, y), gate(x).
p(x, y) :- p(x, z), !s(z), q(z, y).
q(x, y) :- base(x, y).
q(x, y) :- q(x, z), base(z, y).
s(x) :- q(x, y), blocked(y).
sup_tc_bf_r0_0(x) :- magic_tc_bf(x).
sup_tc_bf_r0_1(x, y) :- sup_tc_bf_r0_0(x), sibling_edge(x, y).
tc_bf(x, y) :- sup_tc_bf_r0_1(x, y).
sup_tc_bf_r1_0(x) :- magic_tc_bf(x).
sup_tc_bf_r1_1(x, z) :- sup_tc_bf_r1_0(x), tc_bf(x, z).
sup_tc_bf_r1_2(x, y) :- sup_tc_bf_r1_1(x, z), sibling_edge(z, y).
magic_tc_bf(x) :- sup_tc_bf_r1_0(x).
tc_bf(x, y) :- sup_tc_bf_r1_2(x, y).
out(y) :- p(1, y).
magic_tc_bf(1).
out2(y) :- tc_bf(1, y).
