.decl parent(child:number, par:number)
.input parent
.decl person(x:number)
.input person
.decl sg(x:number, y:number)
.decl notsg(x:number, y:number)
.decl q_notsg(y:number)
.output q_notsg
.decl sup_notsg_bf_r0_0(c0:number)
.decl sup_notsg_bf_r0_1(c0:number)
.decl sup_notsg_bf_r0_2(c0:number, c1:number)
.decl sup_notsg_bf_r0_3(c0:number, c1:number)
.decl magic_sg_bb(c0:number, c1:number)
.decl notsg_bf(c0:number, c1:number)
.decl sup_sg_bb_r0_0(c0:number)
.decl sup_sg_bb_r0_1(c0:number)
.decl sg_bb(c0:number, c1:number)
.decl sup_sg_bb_r1_0(c0:number, c1:number)
.decl sup_sg_bb_r1_1(c0:number, c1:number, c2:number)
.decl sup_sg_bb_r1_2(c0:number, c1:number, c2:number, c3:number)
.decl sup_sg_bb_r1_3(c0:number, c1:number)
.decl sup_sg_bb_r1_4(c0:number, c1:number)
.decl magic_notsg_bf(c0:number)
sup_notsg_bf_r0_0(x) :- magic_notsg_bf(x).
sup_notsg_bf_r0_1(x) :- sup_notsg_bf_r0_0(x), person(x).
sup_notsg_bf_r0_2(x, y) :- sup_notsg_bf_r0_1(x), person(y).
sup_notsg_bf_r0_3(x, y) :- sup_notsg_bf_r0_2(x, y), !sg_bb(x, y).
magic_sg_bb(x, y) :- sup_notsg_bf_r0_2(x, y).
notsg_bf(x, y) :- sup_notsg_bf_r0_3(x, y).
sup_sg_bb_r0_0(x) :- magic_sg_bb(x, x).
sup_sg_bb_r0_1(x) :- sup_sg_bb_r0_0(x), person(x).
sg_bb(x, x) :- sup_sg_bb_r0_1(x).
sup_sg_bb_r1_0(x, y) :- magic_sg_bb(x, y).
sup_sg_bb_r1_1(x, y, xp) :- sup_sg_bb_r1_0(x, y), parent(x, xp).
sup_sg_bb_r1_2(x, y, xp, yp) :- sup_sg_bb_r1_1(x, y, xp), parent(y, yp).
sup_sg_bb_r1_3(x, y) :- sup_sg_bb_r1_2(x, y, xp, yp), sg_bb(xp, yp).
sup_sg_bb_r1_4(x, y) :- sup_sg_bb_r1_3(x, y), x != y.
magic_sg_bb(xp, yp) :- sup_sg_bb_r1_2(x, y, xp, yp).
sg_bb(x, y) :- sup_sg_bb_r1_4(x, y).
magic_notsg_bf(0).
q_notsg(y) :- notsg_bf(0, y).
