.decl base(x:number, y:number, l:number)
.input base
.decl e(x:number, y:number, l:number)
.input e
.decl blocked(x:number, l:number)
.input blocked
.decl q(x:number, y:number, l:number)
.decl s(x:number, l:number)
.decl p(x:number, y:number, l:number)
.decl out(y:number)
.output out
.decl sup_p_bfb_r0_0(c0:number, c1:number)
.decl sup_p_bfb_r0_1(c0:number, c1:number, c2:number)
.decl p_bfb(c0:number, c1:number, c2:number)
.decl sup_p_bfb_r1_0(c0:number, c1:number)
.decl sup_p_bfb_r1_1(c0:number, c1:number, c2:number)
.decl sup_p_bfb_r1_2(c0:number, c1:number, c2:number)
.decl sup_p_bfb_r1_3(c0:number, c1:number, c2:number)
.decl magic_p_bfb(c0:number, c1:number)
.decl magic_s_bb(c0:number, c1:number)
.decl magic_q_bfb(c0:number, c1:number)
.decl sup_s_bb_r0_0(c0:number, c1:number)
.decl sup_s_bb_r0_1(c0:number, c1:number)
.decl sup_s_bb_r0_2(c0:number, c1:number)
.decl s_bb(c0:number, c1:number)
.decl sup_q_bfb_r0_0(c0:number, c1:number)
.decl sup_q_bfb_r0_1(c0:number, c1:number, c2:number)
.decl q_bfb(c0:number, c1:number, c2:number)
.decl sup_q_bfb_r1_0(c0:number, c1:number)
.decl sup_q_bfb_r1_1(c0:number, c1:number, c2:number)
.decl sup_q_bfb_r1_2(c0:number, c1:number, c2:number)
sup_p_bfb_r0_0(x, l) :- magic_p_bfb(x, l).
sup_p_bfb_r0_1(x, l, y) :- sup_p_bfb_r0_0(x, l), e(x, y, l).
p_bfb(x, y, l) :- sup_p_bfb_r0_1(x, l, y).
sup_p_bfb_r1_0(x, l) :- magic_p_bfb(x, l).
sup_p_bfb_r1_1(x, l, z) :- sup_p_bfb_r1_0(x, l), p_bfb(x, z, l).
sup_p_bfb_r1_2(x, l, z) :- sup_p_bfb_r1_1(x, l, z), !s_bb(z, l).
sup_p_bfb_r1_3(x, l, y) :- sup_p_bfb_r1_2(x, l, z), q_bfb(z, y, l).
magic_p_bfb(x, l) :- sup_p_bfb_r1_0(x, l).
magic_s_bb(z, l) :- sup_p_bfb_r1_1(x, l, z).
magic_q_bfb(z, l) :- sup_p_bfb_r1_2(x, l, z).
p_bfb(x, y, l) :- sup_p_bfb_r1_3(x, l, y).
sup_s_bb_r0_0(x, l) :- magic_s_bb(x, l).
sup_s_bb_r0_1(x, l) :- sup_s_bb_r0_0(x, l), q_bfb(x, y, l).
sup_s_bb_r0_2(x, l) :- sup_s_bb_r0_1(x, l), blocked(x, l).
magic_q_bfb(x, l) :- sup_s_bb_r0_0(x, l).
s_bb(x, l) :- sup_s_bb_r0_2(x, l).
sup_q_bfb_r0_0(x, l) :- magic_q_bfb(x, l).
sup_q_bfb_r0_1(x, l, y) :- sup_q_bfb_r0_0(x, l), base(x, y, l).
q_bfb(x, y, l) :- sup_q_bfb_r0_1(x, l, y).
sup_q_bfb_r1_0(x, l) :- magic_q_bfb(x, l).
sup_q_bfb_r1_1(x, l, z) :- sup_q_bfb_r1_0(x, l), q_bfb(x, z, l).
sup_q_bfb_r1_2(x, l, y) :- sup_q_bfb_r1_1(x, l, z), base(z, y, l).
magic_q_bfb(x, l) :- sup_q_bfb_r1_0(x, l).
q_bfb(x, y, l) :- sup_q_bfb_r1_2(x, l, y).
magic_p_bfb(1, 1).
out(y) :- p_bfb(1, y, 1).
