.decl parent(child:number, par:number)
.input parent
.decl person(x:number)
.input person
.decl ancestor(x:number, y:number)
.decl nonancestor(x:number, y:number)
.decl q_nonancestor(y:number)
.output q_nonancestor
.decl sup_nonancestor_bf_r0_0(c0:number)
.decl sup_nonancestor_bf_r0_1(c0:number)
.decl sup_nonancestor_bf_r0_2(c0:number, c1:number)
.decl sup_nonancestor_bf_r0_3(c0:number, c1:number)
.decl magic_ancestor_bb(c0:number, c1:number)
.decl nonancestor_bf(c0:number, c1:number)
.decl sup_ancestor_bb_r0_0(c0:number, c1:number)
.decl sup_ancestor_bb_r0_1(c0:number, c1:number)
.decl ancestor_bb(c0:number, c1:number)
.decl sup_ancestor_bb_r1_0(c0:number, c1:number)
.decl sup_ancestor_bb_r1_1(c0:number, c1:number, c2:number)
.decl sup_ancestor_bb_r1_2(c0:number, c1:number)
.decl magic_nonancestor_bf(c0:number)
sup_nonancestor_bf_r0_0(x) :- magic_nonancestor_bf(x).
sup_nonancestor_bf_r0_1(x) :- sup_nonancestor_bf_r0_0(x), person(x).
sup_nonancestor_bf_r0_2(x, y) :- sup_nonancestor_bf_r0_1(x), person(y).
sup_nonancestor_bf_r0_3(x, y) :- sup_nonancestor_bf_r0_2(x, y), !ancestor_bb(x, y).
magic_ancestor_bb(x, y) :- sup_nonancestor_bf_r0_2(x, y).
nonancestor_bf(x, y) :- sup_nonancestor_bf_r0_3(x, y).
sup_ancestor_bb_r0_0(x, y) :- magic_ancestor_bb(x, y).
sup_ancestor_bb_r0_1(x, y) :- sup_ancestor_bb_r0_0(x, y), parent(x, y).
ancestor_bb(x, y) :- sup_ancestor_bb_r0_1(x, y).
sup_ancestor_bb_r1_0(x, y) :- magic_ancestor_bb(x, y).
sup_ancestor_bb_r1_1(x, y, z) :- sup_ancestor_bb_r1_0(x, y), parent(x, z).
sup_ancestor_bb_r1_2(x, y) :- sup_ancestor_bb_r1_1(x, y, z), ancestor_bb(z, y).
magic_ancestor_bb(z, y) :- sup_ancestor_bb_r1_1(x, y, z).
ancestor_bb(x, y) :- sup_ancestor_bb_r1_2(x, y).
magic_nonancestor_bf(1).
q_nonancestor(y) :- nonancestor_bf(1, y).
